Fix usage of --owner filter during node list
When using --owner filter during node list, the CLI returns
this error:

  list() got an unexpected keyword argument 'owner'

Change-Id: Id751336d8d8cb99e62e465e17114e610f619c520
Story: 2006563
Task: 36660
(cherry picked from commit 89088e2aaa8329bbb98380748e5d9716734e0db6)