Remove Functional Tests
Functional Tests have not been known to not functional since Jan 2024 (https://review.opendev.org/c/openstack/python-ironicclient/+/430904)

The last time they were run in CI before that was in late Aug 2023. (https://review.opendev.org/c/openstack/python-ironicclient/+/891560)

This leaves a very large window for trying to figure out how they went wrong. They were made non-voting in Feb 2024 (https://review.opendev.org/c/openstack/python-ironicclient/+/908828), after which no real efforts were made to fix them.

This patch removes them entirely. For reference, the error as of Nov 1st 2024 when trying to run them is to do with auth.

"AttributeError: 'BaremetalXXXXTests' object has no attribute 'auth_ref'"

Change-Id: I50e8dbcef02ccad03c383a70618d8228db47b876